// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onColorChange();
void onSwitchChange();
void onButtonDownChange();
void onButtonUpChange();

CloudColor color;
int Switch;
bool ButtonDown;
bool ButtonUp;

void initProperties(){

  //ArduinoCloud.addProperty(color, READWRITE, ON_CHANGE, onColorChange);
  ArduinoCloud.addProperty(Switch, READWRITE, ON_CHANGE, onSwitchChange);
  ArduinoCloud.addProperty(ButtonDown, READWRITE, ON_CHANGE, onButtonDownChange, 1);
  ArduinoCloud.addProperty(ButtonUp, READWRITE, ON_CHANGE, onButtonUpChange, 1);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
